### ISSUE TITLE
Bug in macOSX ExpressLRS Configurator v1.4.2

### ISSUE THREAD

**Issue by Martivip** [ExpressLRS/ExpressLRS-Configurator#280]
## Current Behavior

When I launch ExpressLRS Configurator everything works OK, but when i close the Configurator App by clicking red X on the left top corner of the App, the app is being active in background and when I click the App to launch again it displays this below message and the App is being automatically permanently closed.
<img width="360" alt="Message" src="https://user-images.githubusercontent.com/72009313/154133624-a5a39427-661a-4f56-b015-72c3ae901868.png">

**Comment by parkerbjur** [comment]
I have been able to recreate this bug on macOS Monterey 12.2.1 on an m1 macbook air. After the error, relaunching the configurator worked. I will try to look into this soon.

**Comment by sidekickc** [comment]
I get that error when opening Configurator, after quitting the Configurator during a build. Opening a second time does not display the error.

**Comment by Martivip** [comment]
with the new version 1.4.1 issue sill exist

**Comment by Martivip** [comment]
tzw same with 1.4.2

**Comment by Pairan** [comment]
This bug has been there for a looong time but as Bryan already stated: restart it and its gone! ... But yes, it would be nice when it disappears by time :)

**Comment by jurgelenas** [comment]
I have upgraded type-graphql to v1.2.0-RC1 which should solve the issue.

https://github.com/MichalLytek/type-graphql/releases/tag/v1.2.0-rc.1

**Comment by jurgelenas** [comment]
It should be fixed in 1.4.3 release. Please test @Pairan, @parkerbjur, @Martivip.

**Comment by Pairan** [comment]
will report back in

**Comment by Pairan** [comment]
... hey wait ... where has v1.4.3 gone? ... now the new version is stated in V1.4.2 !?

**Comment by Martivip** [comment]
@jurgelenas I've tested with the latest nightly build and no... the issue is still there, where I find 1.4.3 ? :)
